x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "api"
    ports:
      - "8080:8080"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always